### ISSUE TITLE
There is no case in the example

### ISSUE THREAD

**Issue by reallyli** [lubusIN/laravel-decomposer#13]
Correct spelling. Prompt class file not found.

![image](https://cloud.githubusercontent.com/assets/24422856/25171132/5af2adbe-251f-11e7-90f6-5ad90e9481d6.png)

![image](https://cloud.githubusercontent.com/assets/24422856/25171161/6f1367de-251f-11e7-9e1b-81b5c300e9e4.png)

**Comment by introwit** [comment]
@reallyli This should work. Works for me on my Mac , windows & Ubuntu machine. Did you get any error because of this?

**Comment by ajitbohra** [comment]
@reallyli @introwit tested works for me on mac & windows. As mentioned by @introwit that's the namespace in the route file.

**Comment by introwit** [comment]
Thanks @ajitbohra for testing & confirming!

**Comment by reallyli** [comment]
I work in mac development php environment.Thanks @ajitbohra @introwit for instructions.

**Comment by introwit** [comment]
No problem @reallyli , if you face any issues while using Decomposer feel free to create another issue and we will address that as soon as possible :smiley cheers!
