### ISSUE TITLE
Class 'Lubusin\Decomposer\ServiceProvider' not found

### ISSUE THREAD

**Issue by CWallenberg** [lubusIN/laravel-decomposer#15]
```php
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Lubusin\Decomposer\ServiceProvider' not found
```
The service provider in the composer.json does not exist. You have used the name ```ServiceProvider``` but the file name is actually ```DecomposerServiceProvider```.

**Comment by introwit** [comment]
@CWallenberg thank you for pointing it out :) 
- [Fixed and pushed](e060fff7aefacd8664be0f53132986ecf481a802), also [tagged a new release](https://github.com/lubusIN/laravel-decomposer/releases/tag/v1.2.3) considering this a hotfix. 
- `composer require lubusin/laravel-decomposer` should now pull in the latest v1.2.3 :)
