### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Braunson** [lubusIN/laravel-decomposer#18]
I've installed this on a new project, and receive 'file not found' when trying to go to the route. Everything is registered but for some reason the route isn't working.

**Comment by introwit** [comment]
@Braunson which Laravel version?

**Comment by Braunson** [comment]
@introwit 5.5.24

**Comment by introwit** [comment]
It's working for me in an existing 5.5 project. After you did composer require, it should show decomposer in the Discovered packages list in the output of the require command. Then registering the route is the only thing to do. Can you paste the whole error you are receiving?

**Comment by Braunson** [comment]
@introwit No error, just the 'File not found' default Laravel error page. hmm

**Comment by ajitbohra** [comment]
@Braunson closing this feel free to reopen if the error persist.
