### ISSUE TITLE
Support for PHP 5.6

### ISSUE THREAD

**Issue by smayzes** [lubusIN/laravel-decomposer#2]
Would be nice for those of us on projects that haven't upgraded yet.

**Comment by introwit** [comment]
@smayzes Yep correct. Fixed & updated in fa289484bfcff3867be33e3458152676d842aac3 . Now the dependency in v0.1.2 release is PHP >=5.6. Let me know if you face any other issue while using the package. If you feel the issue has been fixed and the fix works correctly you can close the issue.

PS: Thank you for the awesome work you do my maintaining the Larachat slack channel :)
