### ISSUE TITLE
Undefined index: require

### ISSUE THREAD

**Issue by trixanapp** [lubusIN/laravel-decomposer#5]
Hi.
ErrorException (E_NOTICE)
Undefined index: require
in file DecomposerController.php
line 24
$dependencies = $dependenciesArray['require'];
with package caouecs/laravel-lang

this correct example:
$dependencies = $dependenciesArray['require'] ?? ['Dependency' => 'none'];

**Comment by introwit** [comment]
@trixanapp Fixed in b760626839f2d113c1896b4f972b1357d9bb0b4b and released with the [v0.1.4](https://github.com/lubusIN/laravel-decomposer/releases/tag/v0.1.4) , thank you for pointing it out :)
