### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by dducro** [lubusIN/laravel-decomposer#7]
In DecomposerController.php on line: 22

It found files in composer.json that weren't found in the vender dir.
I solved it by adding a file_exists check before reading the file.
But this could be useful info to also display.

**Comment by dducro** [comment]
Hope this helps, let me know if you need any more info.

**Comment by introwit** [comment]
@dducro Looks like a good catch, can you elaborate your complete scenario like was it a package listed in the require field but wasn't installed? The complete scenario would be helpful.

**Comment by dducro** [comment]
We had "illuminate/support": "5.4.*" in our dependency list.
This caused the issue. This is because the folder structure is different for the illuminate packages.
In this case we could just remove it because it was obsolete, in other cases this might not be an option.
I wonder if the folder structure could differ for other packages.

**Comment by introwit** [comment]
@dducro your file exists check makes sense and will be fixed for sure. But assuming you installed illuminate/support separately it should create a folder with the vendor name of illuminate & package name of support that having the composer.json file.Is that correct? I might be wrong on this, just assuming for an example use case

**Comment by dducro** [comment]
@introwit When including illuminate packages without laravel it goes as expected and vendor has a illuminate folder. But in our Laravel projects the folder resides in laravel/framework/src/illuminate, also as expected.

**Comment by introwit** [comment]
@dducro oh okay! Will add the file check in the next release. Thanks for pointing that out :) Also, out of curiosity I want to ask since it already is in the laravel/framework/src/illuminate dir, why have you added it separately in the require field? To warn to use the 5.4.* specific version of Support class maybe I am guessing? Also, you can close the issue if you feel the concerned issue is addressed.

**Comment by dducro** [comment]
@introwit Thanks! :)
No, I don't know how that ended up there.
We have multiple people working on projects, so it might be an old mistake with an laravel upgrade or something.
We do use the illuminate packages out side laravel projects some times, so then we do require them using composer.

**Comment by introwit** [comment]
@dducro No problem, we got a file check to be added because of that haha :) Also you can close the issue if you feel the concerned issue is addressed.
