### ISSUE TITLE
Is it possible to require decomposer within a package?

### ISSUE THREAD

**Issue by dducro** [lubusIN/laravel-decomposer#9]
It's expected that the package is installed in a Laravel project.

DecomposerController::getLaravelEnv()
line: 55

However when including it from a package this line fails because decomposer isn't a dependency of the parent project.

**Comment by introwit** [comment]
If you require it in a package, and on installing that package Decomposer too will get installed in the vendor directory just like the other dependencies. Also why are you making that static call?

**Comment by dducro** [comment]
Lol, I'm not actually making that static call xD
If I add decomposer to a package and install, it will end up in the vendor dir.
But in de getLaravelEnv function in DecomposerController.php on line 55 there is a call to "$packagesArray['lubusin/laravel-decomposer']" This fails if you didn't add the package to the "parent" laravel composer.json. I just want to add the requirement to my package.

**Comment by introwit** [comment]
@dducro but when the package goes live & is installed it will install decomposer in the correct place too. Why would someone need it until there is a complete app supposed to be decomposed?

**Comment by dducro** [comment]
It installs in the correct place. But it throws an error in DecomposerController.php on line 55 if done so. I created a pr: #10

**Comment by introwit** [comment]
@dducro Merged! Thank you for the PR Daniel :)
